hl.curve("easeOutQuint",   { type = "bezier", points = { {0.2, 1},    {0.3, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.6, 0.05}, {0.3, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.7, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.1, 0},    {0.1, 1}     } })
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71, dampening = 15 })

hl.animation({ leaf = "fade",   enabled = true,  speed = 3., bezier = "quick" })
hl.animation({ leaf = "global", enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border", enabled = true,  speed = 5., bezier = "easeOutQuint" })
hl.animation({ leaf = "fadeIn", enabled = true,  speed = 1.7, bezier = "almostLinear" })
hl.animation({ leaf = "layers", enabled = true,  speed = 3.8, bezier = "easeOutQuint" })

hl.animation({ leaf = "windows",   enabled = true,  speed = 4.7, spring = "easy" })
hl.animation({ leaf = "fadeOut",   enabled = true,  speed = 1.4, bezier = "almostLinear" })
hl.animation({ leaf = "layersIn",  enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "windowsIn", enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "layersOut", enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })

hl.animation({ leaf = "windowsOut", enabled = true,  speed = 1.4, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "workspaces", enabled = true,  speed = 1.9, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor", enabled = true,  speed = 7,    bezier = "quick" })

hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.7, bezier = "almostLinear" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.2, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.3, bezier = "almostLinear" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.9, bezier = "almostLinear", style = "fade" })
